[[manager.prepend_keymap]]
on = ["i"]
run = "plugin searchjump"
desc = "searchjump mode"


[[manager.prepend_keymap]]
on = ["i"]
run = "plugin searchjump --args='autocd'"
desc = "searchjump mode(auto cd select folder)"


[[manager.prepend_keymap]]
on = ["f", "g"]
run = "plugin fg"
desc = "find file by content (fuzzy match)"
